## Infinite Overlapping Mixture Model with Binary clusters

In [7]:
%load_ext autoreload
%autoreload 2
import utils, iomm

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


### Synthetic Data

In [20]:
#Generate synthetic data
K=5
N=10
D=8
N_iter=5
alpha_prior = 5

Z = utils.random_z(N,K)
X = utils.random_x(N,D)
theta= utils.random_theta(N,K,D,alpha_prior)

In [21]:
Z

array([[ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  1.],
       [ 0.,  1.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.]])

In [22]:
X

array([[ 0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  1.,  1.,  1.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  1.,  1.,  0.]])

In [23]:
theta

array([[ 0.20377491,  0.16042627,  0.75604591,  0.85953386,  0.18308176,
         0.30085022,  0.08241377,  0.62680755],
       [ 0.4922798 ,  0.12715401,  0.28749961,  0.87227594,  0.30972791,
         0.75124674,  0.8981476 ,  0.25794578],
       [ 0.69039546,  0.09013513,  0.31670739,  0.87459137,  0.58387853,
         0.41744537,  0.90087924,  0.83310639],
       [ 0.72112029,  0.91604134,  0.34534657,  0.29671971,  0.41441477,
         0.8719203 ,  0.85119297,  0.50670103],
       [ 0.46226164,  0.25387066,  0.32458038,  0.313104  ,  0.39459571,
         0.91210862,  0.32414912,  0.85161398]])

#### IOMM algorithm

In [32]:
IOMM = iomm.IOMM(N = N, 
                 K = K, 
                 D = D, 
                 N_iter = N_iter, 
                 Z = Z, 
                 X = X, 
                 theta = theta, 
                 alpha_prior = alpha_prior, 
                 omega = 10,
                 copy_rows = 4)

norm_lh[ 0 ] =  8.10412048767
norm_lh[ 1 ] =  18.3137135632
norm_lh[ 2 ] =  24.1127645796
norm_lh[ 3 ] =  236.246496612
norm_lh[ 4 ] =  13.1868685761
norm_lh = 18.3137135632


In [33]:
Z_hat = IOMM.learning()

iteration n° 0
i = 4
___________1.compute probability of observation i taking category k_________
proba Z=1: 0.0
k= 1
proba Z=1: 0.00689140095237
k= 2
proba Z=1: 0.0295404956908
k= 3
proba Z=1: 0.916820123293
k= 4
proba Z=1: 0.0013398010932
_________2.propose adding new clusters________
accepted for k = 3
i = 5
___________1.compute probability of observation i taking category k_________
proba Z=1: 0.0
k= 1
proba Z=1: 0.042479451889
k= 2
proba Z=1: 2.83950525533
k= 3
proba Z=1: 3.45803259116
k= 4
proba Z=1: 2.24394649242
_________2.propose adding new clusters________
accepted for k = 2
accepted for k = 3
accepted for k = 4
i = 6
___________1.compute probability of observation i taking category k_________
proba Z=1: 0.0
k= 1
proba Z=1: 0.00551134474242
k= 2
proba Z=1: 0.0267328255349
k= 3
proba Z=1: 0.0122929932433
k= 4
proba Z=1: 0.0495707239044
_________2.propose adding new clusters________
i = 7
___________1.compute probability of observation i taking category k_________
proba Z=1: 0.

C:\Users\Zakarya\workspace\bayes_overlapping_clusters\iomm.py:127: RuntimeWarning: overflow encountered in double_scalars
  accept_proba= numerator / denominator
C:\Users\Zakarya\workspace\bayes_overlapping_clusters\iomm.py:149: RuntimeWarning: divide by zero encountered in true_divide
  constant = np.log(theta_vect[d]/(1-theta_vect[d]))
C:\Users\Zakarya\workspace\bayes_overlapping_clusters\iomm.py:153: RuntimeWarning: invalid value encountered in multiply
  for i in range(self.N):
C:\Users\Zakarya\workspace\bayes_overlapping_clusters\iomm.py:149: RuntimeWarning: divide by zero encountered in log
  constant = np.log(theta_vect[d]/(1-theta_vect[d]))



proba Z=1: 0.0
proba Z=1: 3.43057985301
proba Z=1: 0.276747309789
proba Z=1: 0.916820123293
k= 4
proba Z=1: 3.02263828048e-05
_________2.propose adding new clusters________
i = 5
___________1.compute probability of observation i taking category k_________
proba Z=1: 0.0
proba Z=1: 0.508445950298
proba Z=1: 2.83950525533
proba Z=1: 3.45803259116
proba Z=1: 2.24394649242
_________2.propose adding new clusters________
i = 6
___________1.compute probability of observation i taking category k_________
proba Z=1: 0.0
k= 1
proba Z=1: 0.0319741883837
k= 2
proba Z=1: 0.0389985995791
k= 3
proba Z=1: 0.088910917128
proba Z=1: 0.232339100143
_________2.propose adding new clusters________
i = 7
___________1.compute probability of observation i taking category k_________
proba Z=1: 0.0
k= 1
proba Z=1: 0.0319741883837
k= 2
proba Z=1: 0.0389985995791
k= 3
proba Z=1: 0.088910917128
k= 4
proba Z=1: 0.309785466858
_________2.propose adding new clusters________
i = 8
___________1.compute probability of o

theta_k_d proposal: [ 0.65409575  0.2515906   0.78633186  0.4763317   0.82451129]
joint prior current theta: [ 1.  1.  1.  1.  1.]
joint prior prop theta: [ 1.  1.  1.  1.  1.]
likelihood current theta: [  1.           0.32713474   4.27017681   0.53836385  46.33087611]
likelihood current prop: [ 1.          0.33616708  3.680155    0.90960576  4.69837241]
acceptance probability = 0.13252972044
acceptance probability = 0.198268410311
acceptance probability = 0.176550604067
acceptance probability = 0.202496637269
acceptance probability = 0.202496637269


In [ ]:
Z_hat

In [87]:
Z

array([[ 0.,  1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  0.],
       [ 1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.]])

In [31]:
import numpy
numpy.array([1,2])*2

array([2, 4])